### ISSUE TITLE
Rename package to "fprodents"?

### ISSUE THREAD

**Issue by oesteban** [poldracklab/fmriprep-rodents#23]
The hyphen / underscore in the package name is really a headache. I think that migrating everything to ``fprodents`` (similarly to scikit-learn -> sklearn, scikit-image -> skimage, etc.) will really make everything easier at almost no cost. Nobody prevents us to submit two packages to pypi (fmriprep-rodents and fprodents) or only use fmriprep-rodents for Pypi.

WDYT?

**Comment by eilidhmacnicol** [comment]
Seems reasonable to me. 

"fMRIPrep rodents" isn't very catchy, anyway. 

I wouldn't object to continuing with fmriprep-rodents for Pypi alone, I don't really see a need to muddle it with two packages.

**Comment by oesteban** [comment]
cc/ @mgxd @effigies any opinions or detail we might just missed out?

**Comment by effigies** [comment]
No opinions, really. "fp" doesn't really say "fmriprep" to me, but I don't think it's very important.

**Comment by mgxd** [comment]
same, no strong opinion. throwing another name out there: `rmriprep` 🤷

**Comment by oesteban** [comment]
I thought of FmriPrep -> "fp" by analogy to SciKit -> "sk".

@mgxd I can see an issue with dMRIPrep/rodents there. (Also, r-fMRI is many times understood as resting-state fMRI).
