### ISSUE TITLE
Expected structural outputs

### ISSUE THREAD

**Issue by mgxd** [poldracklab/fmriprep-rodents#6]
Below is a list of sMRIPrep outputs. All T1w files will likely be replace with T2w, since that's what `nirodents` primarily uses.
@eilidhmacnicol does this list look right?

- [x] t1w_preproc
        The T1w reference map, which is calculated as the average of bias-corrected and preprocessed T1w images, defining the anatomical space.

- [x] t1w_brain
        Skull-stripped ``t1w_preproc``

- [x] t1w_mask
        Brain (binary) mask estimated by brain extraction.

- [x] t1w_dseg
        Brain tissue segmentation of the preprocessed structural image, including gray-matter (GM), white-matter (WM) and cerebrospinal fluid (CSF).

- [x] t1w_tpms
        List of tissue probability maps corresponding to ``t1w_dseg``.

- [x] std_preproc
        T1w reference resampled in one or more standard spaces.

- [x] std_mask
        Mask of skull-stripped template, in MNI space

- [x]  std_dseg
        Segmentation, resampled into MNI space

- [x] std_tpms
        List of tissue probability maps in MNI space

- [ ] subjects_dir
        FreeSurfer SUBJECTS_DIR

- [x] anat2std_xfm
        Nonlinear spatial transform to resample imaging data given in anatomical space into standard space.

- [x] std2anat_xfm
        Inverse transform of the above.

- [ ] subject_id
        FreeSurfer subject ID

- [ ] t1w2fsnative_xfm
        LTA-style affine matrix translating from T1w to FreeSurfer-conformed subject space

- [ ] fsnative2t1w_xfm
        LTA-style affine matrix translating from FreeSurfer-conformed subject space to T1w

- [ ] surfaces
        GIFTI surfaces (gray/white boundary, midthickness, pial, inflated)

**Comment by eilidhmacnicol** [comment]
LGTM.

Although the std_* outputs won't be in "MNI space", but whatever standard space is associated with the template (probably WHS, for instance).
